ALTER TABLE stadium ADD COLUMN cep VARCHAR(20);
ALTER TABLE stadium ADD COLUMN street VARCHAR(100);
ALTER TABLE stadium ADD COLUMN neighborhood VARCHAR(100);
ALTER TABLE stadium ADD COLUMN city VARCHAR(100);
ALTER TABLE stadium ADD COLUMN state_code VARCHAR(20);